import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from '../context/ThemeContext';
import Navbar from "@/components/navigations/Navbar";
import { GeistSans } from "geist/font/sans";
import {ApolloWrapper} from "@/provider/ApolloWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider>
          <html lang="en" className={GeistSans.className}>
          <body>
          <ApolloWrapper>
          <Navbar/>
              {children}
           </ApolloWrapper>
          </body>
          </html>
      </ThemeProvider>
  );
}